[workspace]
resolver = "3"
members = [
    "godot_composition_core",
    "godot_composition",
    "godot_composition_tests"
]

[workspace.dependencies]
godot = { version = "0.3.1", features = ["api-4-4", "register-docs", "experimental-threads"] }